name: lint
on:
  - push
  - pull_request

jobs:
  reuse:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -m pip install reuse
      - run: python -m reuse lint
